# Site settings
title: Memphis River Parks Partnership
email: info@memphisriverparks.org
author:
description:
url: http://memphisriverparks.org

# Build settings
# permalink: :title/
sass:
  sass_dir: css